export const tourTypes = {
    SET_PROVINCE: 'SET_PROVINCE',
    SET_LOCATION: 'SET_PUBLISHSER',
    SET_ALL_LOCATION : 'SET_ALL_LOCATION',
    ADD_LOCATION_SUCCESS: 'ADD_LOCATION_SUCCESS',
    ADD_LOCATION_FAIL: 'ADD_LOCATION_FAIL',
    UPDATE_LOCATION_SUCCESS: 'UPDATE_LOCATION_SUCCESS',
    UPDATE_LOCATION_FAIL: 'UPDATE_LOCATION_FAIL',
    RESET_LOCATION: 'RESET_LOCATION',
    LOCATION_SET_PAGE: 'LOCATION_SET_PAGE',
    LOCATION_SET_TOTAL_PAGE: 'LOCATION_SET_TOTAL_PAGE',
    SET_TOUR_DESIGN : 'SET_TOUR_DESIGN',
    ACCEPT_TOUR_DESIGN_SUCCESS : 'ACCEPT_TOUR_DESIGN_SUCCESS',
    ACCEPT_TOUR_DESIGN_FAIL : 'ACCEPT_TOUR_DESIGN_FAIL',
    RESET_TOUR_DESIGN : 'RESET_TOUR_DESIGN',
    TOUR_DESIGN_SET_PAGE : 'TOUR_DESIGN_SET_PAGE',
    TOUR_DESIGN_SET_TOTAL_PAGE : 'TOUR_DESIGN_SET_TOTAL_PAGE',
    SET_TOUR : 'SET_TOUR',
    ADD_TOUR_SUCCESS : 'ADD_TOUR_SUCCESS',
    ADD_TOUR_FAIL : 'ADD_TOUR_FAIL',
    UPDATE_TOUR_SUCCESS : 'UPDATE_TOUR_SUCCESS',
    UPDATE_TOUR_FAIL : 'UPDATE_TOUR_FAIL',
    RESET_TOUR : 'RESET_TOUR',
    TOUR_SET_PAGE : 'TOUR_SET_PAGE',
    TOUR_SET_TOTAL_PAGE : 'TOUR_SET_TOTAL_PAGE',
    SET_CATEGORY_TOUR : 'SET_CATEGORY_TOUR'

}

export const userTypes = {
    SET_USER: 'SET_USER',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAIL: 'ADD_USER_FAIL',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',
    RESET_USER: 'RESET_USER',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    SET_PAGE: 'SET_PAGE',
    SET_TOTAL_PAGE:'SET_TOTAL_PAGE'
}

export const homeTypes = {
    SET_TOP_PRODUCT:' SET_TOP_PRODUCT'
}

export const contactTypes = {
    SET_CONTACT : 'SET_CONTACT',
    SET_CONTACT_PAGE : 'SET_CONTACT_PAGE',
    SET_CONTACT_TOTAL_PAGE : 'SET_CONTACT_TOTAL_PAGE'
}

export const providerTypes = {
    SET_PROVIDER : 'SET_PROVIDER',
    ADD_PROVIDER_SUCCESS : 'ADD_PROVIDER_SUCCESS',
    ADD_PROVIDER_FAIL : 'ADD_PROVIDER_FAIL',
    UPDATE_PROVIDER_SUCCESS : 'UPDATE_PROVIDER_SUCCESS',
    UPDATE_PROVIDER_FAIL : 'UPDATE_PROVIDER_FAIL',
    RESET_PROVIDER : 'RESET_PROVIDER',
    SET_PROVIDER_PAGE : 'SET_PROVIDER_PAGE',
    SET_PROVIDER_TOTAL_PAGE : 'SET_PROVIDER_TOTAL_PAGE',
    SET_USER_PROVIDER : 'SET_USER_PROVIDER',
    SET_ALL_PROVIDER : 'SET_ALL_PROVIDER'
    
}